version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: postgress_bb
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data-db:/data-db
    ports:
      - 5432:5432